# Generated by Django 3.1.5 on 2021-11-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_feedback_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='places'),
        ),
    ]
